api_platform:
    title: Ressource Relational
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
        multipart : ['multipart/form-data']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 50
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage # Default value
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
            apiKey:
                name: X-API-Key
                type: header