nelmio_api_doc:
    documentation:
        info:
            title: Ressource Relationelle
            description: Une API d'OpenClassrooms avec des livres, des autrices et des auteurs !
            version: 1.0.0
        components:
#            securitySchemes:
#                bearerAuth:
#                    type: http
#                    scheme: bearer
#                    bearerFormat: JWT
#                    in: header
#                    name: Authorization # or another header name
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc