vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        ressources_image:
            uri_prefix: /images/ressources
            upload_destination: '%kernel.project_dir%/public/images/ressources'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
