image: docker:latest

stages:
  - build
  - test
  - deploy

services:
  - docker:dind

before_script:
  - docker-compose up -d
  - docker-compose exec -T php composer install

cache:
  paths:
    - /cache/composer

build:
  stage: build
  script:
    - docker-compose exec -T php bin/console cache:clear
    - docker-compose exec -T php bin/console doctrine:migrations:migrate --no-interaction
    - docker-compose exec -T php vendor/bin/phpcs --standard=PSR2 src/
    - docker-compose exec -T php vendor/bin/phpcbf --standard=PSR2 src/

test:
  stage: test
  script:
    - docker-compose exec -T php vendor/bin/phpunit

deploy:
  stage: deploy
  script:
    - docker-compose exec -T php bin/console deploy:run
  only:
    - main
