services:
  app:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: symfony_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - /var/www/ressource:/var/www/html
    environment:
      - APP_ENV=prod
    depends_on:
      - db
    networks:
      - symfony

  webserver:
    image: nginx:alpine
    container_name: symfony_webserver
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - symfony

  db:
    image: mysql:8.0-debian
    container_name: symfony_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - symfony

volumes:
  db-data:

networks:
  symfony:
    driver: bridge
