services:
  app:
    image: php:8.2-fpm
    container_name: symfony_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - /var/www/ressource:/var/www/html
    environment:
      - APP_ENV=prod
    networks:
      - symfony

  webserver:
    image: nginx:alpine
    container_name: symfony_webserver
    restart: unless-stopped
    volumes:
      - /var/www/ressource/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/ww/ressource:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - symfony

  db:
    image: mysql:8.0-debian
    container_name: symfony_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ressource
      MYSQL_USER: base_user
      MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - symfony

volumes:
  db-data:

networks:
  symfony:
    driver: bridge
